[book]
authors = ["Jonathan Pallant (Ferrous Systems)"]
language = "en"
multilingual = false
src = "src"
title = "Why Ferrocene?"

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["po"]
